### ISSUE TITLE
Plugin arch wishlist items of 2023-05

### ISSUE THREAD

**Issue by samiebee43** [WasatchPhotonics/ENLIGHTEN#151]
- [ ] resizable pandas table
- [ ] move plugin higher up on sidebar

**Comment by samiebee43** [comment]
> I'm unsure if moving to the "very top" of the sidebar is ideal.  Personally I might vote for between (Detector Control, X-Axis) or (X-Axis, Scan Averaging).  I think laser control and detector control (integration time) should remain at the top though.  Making it harder to find (unexpectedly moving) the button to turn off the laser is almost a safety issue.


_Originally posted by @mzieg in https://github.com/WasatchPhotonics/ENLIGHTEN/issues/132#issuecomment-1538697430_

**Comment by samiebee43** [comment]
Not sure if this is `2 - required` or `8 - wishlist`. What say you? @mzieg

**Comment by mzieg** [comment]
I'd split it into two issues. The resizeable table is an 8, moving plugins higher is a 4.  Partly because the first task is "somewhat hard" and the second is "extremely easy" (cut-and-paste in vim).

I'd also think carefully about (when moving plugins higher) moving the plugin selection and connect checkbox to the top of the repositioned widget, so you don't even have to jump to Settings and back when selecting and activating plugins.
